#!/bin/sh /etc/rc.common
START=90
STOP=10

USE_PROCD=1
PROG=/usr/bin/ssservice
CONFIGFILE=/etc/sss/local.json
ACLFILE=/etc/sss/sss.acl

start_service() {
	procd_open_instance
	procd_set_param command $PROG local -d --acl $ACLFILE -c $CONFIGFILE
	procd_set_param file $CONFIGFILE
	procd_set_param respawn
	procd_close_instance
}

stop_service()
{
	service_stop $PROG
}

service_triggers()
{
	procd_add_reload_trigger "ssservice"
}