name: SSR Build Releases
on:
  push:
    paths:
      - '**/*-ssr.version'

env:
  CARGO_TERM_COLOR: always
  SSR_VERSION: 1.12.6

jobs:
  build-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-musl

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            repository: 'shadowsocks/shadowsocks-rust'
            ref: 'master'
      - name: Install cross
        run: cargo install cross

      - name: Build ${{ matrix.target }}
        timeout-minutes: 120
        run: |
          compile_target=${{ matrix.target }}
          if [[ "$compile_target" == *"-linux-"* || "$compile_target" == *"-apple-"* ]]; then
            compile_features="-f local-redir -f local-tun -f local-dns"
          fi
          if [[ "$compile_target" == "mips-"* || "$compile_target" == "mipsel-"* || "$compile_target" == "mips64-"* || "$compile_target" == "mips64el-"* ]]; then
            sudo apt-get update -y && sudo apt-get install -y upx;
            if [[ "$?" == "0" ]]; then
              compile_compress="-u"
            fi
          fi
          cd build
          ./build-release -t ${{ matrix.target }} $compile_features $compile_compress
      - name: Upload package to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
        with:
          name: ${{ env.IPKG_VERSION }}
          tag_name: ${{ env.IPKG_VERSION }}
          files: build/release/*
